# Generated by Django 3.1.7 on 2023-07-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=25)),
                ('manager_name', models.CharField(max_length=25)),
                ('inspected_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe', models.CharField(blank=True, max_length=50)),
                ('Department', models.CharField(blank=True, max_length=25)),
                ('target_correction_date', models.DateField(blank=True, null=True)),
                ('basic_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_app.basicdetails')),
            ],
        ),
    ]
